Feat/pendle yt
dolomite-exchange/dolomite-margin-modules pull request #8
Opened 2023-07-21 17:58 UTC by BowTiedOriole

I am creating this now for visibility. It is not quite ready as my auto-formatter made a bunch of changes that I need to go back and fix and then do my final review.

I just like to be able to look at it in git when I do my personal final reviews.

2023-07-25 00:08 UTC, BowTiedOriole commented
@coreycaplan3 Sorry for the linting issues. I have fixed that and figured out that slight math issue that we discussed last week. I was impersonating the vault and depositing USDC which was accruing interest and throwing off the math.

I tried to run yarn coverage but my computer crashed. I'm going to try again, but wanted to comment that the code is done.

2023-08-14 18:23 UTC, coreycaplan3 requested changes
See my inline comments

2023-08-14 18:23 UTC, coreycaplan3 commented on contracts/external/pendle/PendlePtGLP2024IsolationModeVaultFactory.sol
> +        emit PendleGLPRegistrySet(_pendleGLPRegistry);
Don't rename the event either

2023-08-14 18:23 UTC, coreycaplan3 commented on test/external/pendle/PendleYtGLP2024IsolationModeTokenVaultV1.ts
> +  describe('#transferIntoPositionWithOtherToken', () => {
Rename to `transferFromPositionWithOtherToken`

Be sure to add the new test cases for the added logic discussed in the corresponding Solidity file

2023-08-18 17:12 UTC, coreycaplan3 approved these changes

2023-08-19 01:14 UTC, coreycaplan3 approved these changes

2023-08-19 01:41 UTC, merged